"""Long-term memory for the chat agent.

Persistence lives here rather than under ``src/backend/tools/`` because three different
layers read it: the memory tools, the chat turn builder, and session deletion.
Mirrors how ``src/backend/sessions/`` owns its own storage.
"""

from __future__ import annotations

from .extraction import ExtractionCandidate, ExtractionOutcome, MemoryExtractor
from .models import (
    CATEGORIES,
    DEFAULT_CATEGORY,
    DEFAULT_STORE_PATH,
    EXTRACTION_TAG_PREFIX,
    ID_PATTERN,
    MAX_FORGET_DELETES,
    MAX_QUERY_CHARS,
    MAX_QUERY_TERMS,
    MAX_SCOPE_ID_CHARS,
    MAX_TAG_CHARS,
    MAX_TAGS,
    MAX_TOOL_CALLS_PER_TURN,
    MIN_TERM_CHARS,
    RECORD_FIELDS,
    SCHEMA_VERSION,
    SCOPES,
    MemoryCategory,
    MemoryDocument,
    MemoryRecord,
    MemoryScope,
    utc_now_iso,
)
from .recall import (
    MEMORY_BUDGET,
    MEMORY_NOTE_LABEL,
    MEMORY_NOTE_MARKER,
    MemoryCallBudget,
    build_memory_note,
    build_turn_messages,
    format_record,
    format_records,
)
from .relevance import (
    derive_query_terms,
    normalize_content,
    rank_records,
    relevance_score,
    searchable_text,
    timestamp_epoch,
)
from .scheduler import ExtractionScheduler
from .secrets import SECRET_PATTERNS, find_secret_in_any, find_secret_match
from .serialization import CorruptDocumentError, parse_document, serialize_document
from .store import (
    ForgetOutcome,
    MemoryPathError,
    MemoryStore,
    MemoryStoreError,
    MemoryWriteError,
    RecallOutcome,
    SaveOutcome,
    get_memory_store,
    in_scope_records,
    reset_store_cache,
    resolve_store_path,
)
from .transcript import (
    ASSISTANT_LABEL,
    MAX_SLICE_MESSAGES,
    TRUNCATION_MARKER,
    USER_LABEL,
    count_turns,
    is_memory_note,
    message_role,
    normalize_message_content,
    render_slice,
    select_slice,
)
from .watermark import (
    MAX_WATERMARK,
    WATERMARK_KEY,
    InMemoryWatermarkStore,
    WatermarkStore,
    coerce_watermark,
)

__all__ = [
    "CATEGORIES",
    "DEFAULT_CATEGORY",
    "DEFAULT_STORE_PATH",
    "EXTRACTION_TAG_PREFIX",
    "ExtractionCandidate",
    "ExtractionOutcome",
    "ExtractionScheduler",
    "ID_PATTERN",
    "MAX_FORGET_DELETES",
    "MAX_QUERY_CHARS",
    "MAX_QUERY_TERMS",
    "MAX_SLICE_MESSAGES",
    "MAX_SCOPE_ID_CHARS",
    "MAX_TAGS",
    "MAX_TAG_CHARS",
    "MAX_TOOL_CALLS_PER_TURN",
    "MAX_WATERMARK",
    "MIN_TERM_CHARS",
    "RECORD_FIELDS",
    "SCHEMA_VERSION",
    "SCOPES",
    "SECRET_PATTERNS",
    "MEMORY_BUDGET",
    "MEMORY_NOTE_LABEL",
    "MEMORY_NOTE_MARKER",
    "CorruptDocumentError",
    "ForgetOutcome",
    "MemoryCallBudget",
    "MemoryCategory",
    "MemoryDocument",
    "MemoryPathError",
    "MemoryRecord",
    "MemoryScope",
    "MemoryStore",
    "MemoryStoreError",
    "MemoryExtractor",
    "MemoryWriteError",
    "RecallOutcome",
    "SaveOutcome",
    "ASSISTANT_LABEL",
    "TRUNCATION_MARKER",
    "USER_LABEL",
    "WATERMARK_KEY",
    "WatermarkStore",
    "InMemoryWatermarkStore",
    "build_memory_note",
    "build_turn_messages",
    "coerce_watermark",
    "count_turns",
    "derive_query_terms",
    "find_secret_in_any",
    "find_secret_match",
    "format_record",
    "format_records",
    "get_memory_store",
    "in_scope_records",
    "is_memory_note",
    "message_role",
    "normalize_message_content",
    "normalize_content",
    "parse_document",
    "rank_records",
    "relevance_score",
    "reset_store_cache",
    "resolve_store_path",
    "render_slice",
    "searchable_text",
    "serialize_document",
    "select_slice",
    "timestamp_epoch",
    "utc_now_iso",
]
